<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet"
	href="<c:url value="/resources/bootstrap/css/bootstrap.min.css"/>">
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="<c:url value="/resources/jquery/jquery-1.11.3.min.js"/>"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="<c:url value="/resources/bootstrap/js/bootstrap.min.js"/>"></script>
<link rel="shortcut icon"
	href="<c:url value="/resources/img/favicon.ico"/>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
